# This is a GitHub CI workflow for the NCEPLIBS-nemsio project.
#
# This workflow runs the intel compiler.
#
# Ed Hartnett 1/12/23
name: Intel
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  Intel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compilers: ["oneapi", "classic"]

    steps:

    - name: checkout
      uses: actions/checkout@v4
      with:
        path: nemsio
        submodules: true


      # See https://software.intel.com/content/www/us/en/develop/articles/oneapi-repo-instructions.html
    - name: "Install Intel"
      uses: NOAA-EMC/ci-install-intel-toolkit@develop
      with:
        install-mpi: true

    - name: "Compiler setup"
      run: |
        if [ ${{ matrix.compilers }} == "oneapi" ]; then
          echo "export CC=mpiicx FC=mpiifx" >> ~/.bash_profile
        elif [ ${{ matrix.compilers }} == "intel" ]; then
          echo "export CC=mpiicc FC=mpiifort" >> ~/.bash_profile
        fi

    - name: "Build dependencies"
      uses: NOAA-EMC/ci-build-nceplibs@develop
      with:
        bacio-version: develop
        w3emc-version: develop
        w3emc-cmake-args: -DBUILD_WITH_BUFR=OFF

    - name: Build and test
      run: |
        cmake -B ${{ github.workspace }}/nemsio/build -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-bacio;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-w3emc" ..
        cmake --build ${{ github.workspace }}/nemsio/build --parallel 2 VERBOSE=1
        cmake --build ${{ github.workspace }}/nemsio/build --target=test --verbose --output-on-failure --rerun-failed
