name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      FC: gfortran-9
      CC: gcc-9

    steps:

    - name: install-mpi
      run: |
        sudo apt-get install libmpich-dev doxygen gcovr

    - name: "Build dependencies"
      uses: NOAA-EMC/ci-build-nceplibs@develop
      with:
        bacio-version: develop
        w3emc-version: develop
        w3emc-cmake-args: -DBUILD_WITH_BUFR=OFF

    - name: checkout
      uses: actions/checkout@v2
      with:
        path: nemsio
        submodules: true

    - name: build
      run: |
        cd nemsio
        mkdir build
        cd build
        cmake .. -DENABLE_DOCS=ON -DENABLE_TESTS=ON -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-bacio;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-w3emc -DCMAKE_Fortran_FLAGS="-g -fprofile-abs-path -fprofile-arcs -ftest-coverage -O0"
        make -j2

    - name: test
      run: |
        cd $GITHUB_WORKSPACE/nemsio/build
        ctest --output-on-failure

    - name: run-gcovr
      run: |
        cd $GITHUB_WORKSPACE/nemsio/build
        gcovr -r .. -v  --html-details -o test-coverage.html

    - name: upload-test-coverage
      uses: actions/upload-artifact@v2
      with:
        name: nemsio-test-coverage
        path: nemsio/build/*.html
